stages:
  - lint
  - build
  - deploy

lint:
  image: node:16-alpine
  before_script:
    - cd src
    - npm install
  script:
    - npm run prepush
  only:
    - main

build:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main

deploy:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker run -d -p 8000:8000 --name music-player $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main
  environment:
    name: production
